### PR TITLE
Fix up multirepo command output

### PR DESCRIPTION
**Pull request by mbolivar**
This PR fixes usability issues with west's multi-repo command output.

### CODE REVIEW

**Comment by carlescufi** [comment]
The meat of this was already reviewed in the previously closed PR, correct @mbolivar?

**Comment by mbolivar** [comment]
Correct, just a rebase + bootstrapper fixes + new version

**Comment by mbolivar** [comment]
Pushed an update to a commit message; no code changes

**Comment by mbolivar** [comment]
> Re-approving, but please ensure #232 goes in before releasing 0.5.5

Sure, no problem, but we can always cut 0.5.6 if needed, no?

**Comment by tejlmand** [comment]
> > Re-approving, but please ensure #232 goes in before releasing 0.5.5
> 
> Sure, no problem, but we can always cut 0.5.6 if needed, no?

we can, but I feel bad in releasing when we know there is a major bug.

**Pull request merged**
