### PR TITLE
Add Bash auto-completion script

### PR DESCRIPTION
**Pull request by ulfalizer**
Currently completes flags and subcommand names.

Fixes: #24

### CODE REVIEW

**Comment by ulfalizer** [comment]
CC @carlescufi

**Comment by ulfalizer** [comment]
This initial version just has command name and flag completion.

We need to think about installation too, unless we want users to manually `source` it.

**Comment by carlescufi** [comment]
Thanks! Can you please add installation instructions as well?

**Comment by ulfalizer** [comment]
Added some reminders to the West source code and installation instructions to the README.

**Pull request merged**
