### PR TITLE
More import tests

### PR DESCRIPTION
**Pull request by mbolivar**
Add some more regression tests.

### CODE REVIEW

**Comment by mbolivar** [comment]
There are still some coverage numbers I'm not too happy with overall, specifically these:

```
----- coverage: platform linux, python 3.8.1-final-0 -----------
Name                                         Stmts   Miss  Cover
----------------------------------------------------------------
west/app/main.py                               374     94    75%
west/app/project.py                            484     93    81%
```

But I think we have good-enough coverage of the manifest import feature with this PR. Please let me know if you disagree @carlescufi / @tejlmand.

If not, I'll add manifest import loop detection and testing and resolve the other remaining specific tasks mentioned in #221 and I think it's time for 0.7.0rc1.

**Comment by mbolivar** [comment]
By the way, if you want to get the source code annotated by coverage status as HTML, you can run this locally:

```
$ tox -- --cov-report=html:$PWD/cov-html 
```

This data includes coverage done in subprocess invocations of west by test_project.py.

**Comment by carlescufi** [comment]
@tejlmand could you please review, even if it's just a quick review? This would unblock #364

**Comment by mbolivar** [comment]
Thanks!

**Pull request merged**
