### PR TITLE
Always decode manifests with utf-8; not just most of the time

### PR DESCRIPTION
**Pull request by marc-hb**
3 commits.

- Two de-duplication commits with no effect
- Consistently decode manifests with utf-8

This is a "larger" alternative to #710

### CODE REVIEW

**Comment by marc-hb** [comment]
macos failures in https://github.com/zephyrproject-rtos/west/actions/runs/9275086435/job/25518959121?pr=711 are unrelated, will be fixed by #712

**Comment by marc-hb** [comment]
> This is a "larger" alternative to #710 

@ylz0923 can you please fetch and test this?

**Comment by ylz0923** [comment]
It test success in the case(project.py: Specify the manifest file to use UTF-8 encoding #710).

**Comment by mbolivar** [comment]
@marc-hb did you look into the CI failures?

**Comment by marc-hb** [comment]
> @marc-hb did you look into the CI failures?

Yes: see #712 mentioned above.

**Review by carlescufi — APPROVED** [review]

**Pull request merged**
