### PR TITLE
app: fix control-C behavior

### PR DESCRIPTION
**Pull request by mbolivar-nordic**
We shouldn't be exiting 0 on interrupt, because this means we did not successfully complete. Use better platform-specific exception handling instead. See comments for details.

Fixes: #636

### CODE REVIEW

**Comment by mbolivar-nordic** [comment]
Hmm, this isn't working the way I expect on Windows. DNM

**Comment by mbolivar-nordic** [comment]
On a final note, I also verified that this doesn't affect control-C handling when you enter that within a gdb subprocess underneath `west debug` (on Linux). The existing correct behavior is maintained: the signal is delivered to gdb, which catches it and returns to the debugger REPL instead of exiting any processes.

**Review by marc-hb — COMMENTED** [review]
The comments in the source code look very relevant and useful but let's pretend just for argument's sake that the person reading the code has no time or not enough background to dive deep into a 8 years old python bug or CPython source code. Any ressemblance with any real person is of course a pure coincidence.

The pointers seem extremely useful for a reader wondering whether this sort of black magic is the correct _solution_ or not. But long before that, it would be good to have a very basic introduction to the _problems_ solved by this code. This could be done by answering some very basic questions like "Why catch `KeyboardInterrupt` at all; why doesn't Python automagically does the right thing? Does it in a later/future Python? Is this mimicking newer Python versions to support older Python versions?" and "Why is some `signal` propagation required on Linux but not on Windows?"

You get the idea.

**Comment by marc-hb** [comment]
> the person reading the code has no time or not enough background to dive deep into a 8 years old python bug or CPython source code.

Typically: someone trying to understand why things still don't work as expected on their system and _testing_ this code in various ways. Describing the problems tentatively solved by this exception handling code then guide the testing and the filing of a good bug with good reproduction steps.

**Comment by mbolivar-nordic** [comment]
@marc-hb I have updated the commit message with the requested details; thanks for review.

**Comment by marc-hb** [comment]
Thanks for the very detailed commit message, I'm learning a lot. However this is a lot more  than what I was asking and not _where_ I was asking it.

Looking at the newer commit message, now I know much better what I was asking. I'd like this new sentence in the _source code_, not just in the commit message:

> West catches KeyboardInterrupt because we do not want to dump stack 

And maybe this one too:

> On Unix, exiting with the expected status code is not enough, however.
If that's all we do, the calling shell will not detect that we were
interrupted.

If I had written this code myself I may have added a few more comments in the source code but you seem reluctant to add "too mundane" (?) comments in the source so I'm focusing on the essentials.

**Review by marc-hb — APPROVED** [review]
> basic assumed knowledge for people responsible for writing Python CLI apps

I can imagine it's second nature for these people but thanks for spending a one-line comment for the majority of other people: including very many people comfortable with Python yet who never created a new Python CLI app from scratch.

Without this intro, they wonder what is the point of all this seriously scary voodoo in the except block.

**Comment by marc-hb** [comment]
> > basic assumed knowledge for people responsible for writing Python CLI apps

> seriously scary voodoo in the except block.

If it's basic knowledge, why does Python make it so hard and why didn't you get it right the first time? That does not make sense to me.

Never mind.

**Pull request merged**
